config/routes.rb
Rails.application.routes.draw do

  root "recipes#index"
  resources :recipes

  get 'pages/about' => 'pages#about'
  get 'pages/privacy' => 'pages#privacy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true

  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :steps, allow_destroy: true

  mount_uploader :image, ImageUploader

end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def privacy
  end

  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:remove_image, :image, :title, :description, ingredients_attributes:[:id, :content, :_destroy], steps_attributes:[:id, :direction, :_destroy] )
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Recipe App", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to 'New Recipe', new_recipe_path%>
            </li>
            <li>
              <%= link_to "About", pages_about_path %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="col-md-5 col-md-offset-4">
    <h1>About Page Placeholder</h1>
    <%= link_to "Home Page", root_path, class: "btn" %>
  </div>
</div>

app/views/pages/privacy.html.erb
<div class="container">
  <div class="col-md-5 col-md-offset-4">
    <h1>This is the PRIVACY PAGE</h1>
    <%= link_to "Home Page", root_path, class: "btn" %>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= form_for(recipe) do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3>Add Image</h3>
  <div class="form-group">
    <%= f.file_field :image %>
      <% if @recipe.image? %>
        <%= image_tag @recipe.image.url, class: "recipe-show" %>
        <%= f.check_box :remove_image %>
        Remove Image
      <% end %>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, id: :recipe_title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, id: :recipe_description, class: "form-control" %>
  </div>

  <h3>Add Ingredients</h3>
  <div class="form-group">
    <%= f.nested_fields_for :ingredients do |ingredient| %>
      <%= ingredient.text_field :content %>
      <%= ingredient.remove_nested_fields_link %>
      <% end %>
    <%= f.add_nested_fields_link :ingredients %>
  </div>

  <h3>Add Steps</h3>
  <div class="form-group">
    <%= f.nested_fields_for :steps do |step| %>
      <%= step.text_field :direction %>
      <%= step.remove_nested_fields_link %>
      <% end %>
    <%= f.add_nested_fields_link :steps %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe, class: "btn" %> |
<%= link_to 'Back', recipes_path, class: "btn" %>

app/views/recipes/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Recipes</h1>
    <div class="row">

      <% @recipes.each do |recipe| %>
        <div class="col-md-4">
          <div class="recipe-box">
            <% if recipe.image? %>
              <%= link_to (image_tag recipe.image.url, class: "recipe-index"), recipe %>
            <% end %>
              <ul>
                <li><%= recipe.title %></li>
                <li><%= recipe.description %></li>
                <li><%= link_to 'Show', recipe %> |
                <%= link_to 'Edit', edit_recipe_path(recipe) %> |
                <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
          </div><!-- /.reciper-box -->
        </div><!-- /.col-md-4 -->
      <% end %>

    </div><!-- /.row -->
  <br>

  <%= link_to 'New Recipe', new_recipe_path, class: "btn" %>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <div class="col-md-5 col-md-offset-4">
    <h1>New Recipe</h1>

    <%= render 'form', recipe: @recipe, class: "btn" %>

    <%= link_to 'Back', recipes_path, class: "btn" %>
  </div>
</div>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-md-5 col-md-offset-4">
      <% if @recipe.image? %>
      <%= image_tag @recipe.image.url, class: "recipe-show" %>
      <!-- <%= image_tag(@recipe.image_url) %> -->
      <!-- <%= image_tag(@recipe.image.url(:thumb)) %> -->
      <% end %>
    </div>
  </div>

  <br><hr><br>

  <div class="row">
    <div class="col-md-5 col-md-offset-4">
      <p>
        <strong>Title:</strong>
        <%= @recipe.title %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @recipe.description %>
      </p>

      <h3>Ingredients</h3>
      <ul>
        <% for @ingredient in @recipe.ingredients %>
        <li><%= @ingredient.content %></li>
        <% end %>
      </ul>

      <h3>Steps</h3>
      <ol>
        <% for @step in @recipe.steps  %>
        <li><%= @step.direction %></li>
        <% end %>
      </ol>

      <%= link_to 'Edit', edit_recipe_path(@recipe), class: "btn" %>
      |
      <%= link_to 'Back', recipes_path, class: "btn" %>
    </div>
  </div>
</div>